/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAccountsRouteImport } from './routes/app/accounts'
import { Route as AppBudgetRouteImport } from './routes/app/budget'
import { Route as AppCashFlowRouteImport } from './routes/app/cash-flow'
import { Route as AppInvestmentsRouteImport } from './routes/app/investments'
import { Route as AppNetWorthRouteImport } from './routes/app/net-worth'
import { Route as AppRecurringRouteImport } from './routes/app/recurring'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as AppAccountsAccountIdRouteImport } from './routes/app/accounts.$accountId'
import { Route as AppSettingsCategoriesRouteImport } from './routes/app/settings.categories'
import { Route as AppSettingsRulesRouteImport } from './routes/app/settings.rules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppCashFlowRoute = AppCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppNetWorthRoute = AppNetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppSettingsCategoriesRoute = AppSettingsCategoriesRouteImport.update({
  id: '/settings/categories',
  path: '/settings/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRulesRoute = AppSettingsRulesRouteImport.update({
  id: '/settings/rules',
  path: '/settings/rules',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/app/accounts': typeof AppAccountsRouteWithChildren
  '/app/budget': typeof AppBudgetRoute
  '/app/cash-flow': typeof AppCashFlowRoute
  '/app/investments': typeof AppInvestmentsRoute
  '/app/net-worth': typeof AppNetWorthRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/': typeof AppIndexRoute
  '/app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/app/settings/categories': typeof AppSettingsCategoriesRoute
  '/app/settings/rules': typeof AppSettingsRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/app/accounts': typeof AppAccountsRouteWithChildren
  '/app/budget': typeof AppBudgetRoute
  '/app/cash-flow': typeof AppCashFlowRoute
  '/app/investments': typeof AppInvestmentsRoute
  '/app/net-worth': typeof AppNetWorthRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app': typeof AppIndexRoute
  '/app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/app/settings/categories': typeof AppSettingsCategoriesRoute
  '/app/settings/rules': typeof AppSettingsRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/app/accounts': typeof AppAccountsRouteWithChildren
  '/app/budget': typeof AppBudgetRoute
  '/app/cash-flow': typeof AppCashFlowRoute
  '/app/investments': typeof AppInvestmentsRoute
  '/app/net-worth': typeof AppNetWorthRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/': typeof AppIndexRoute
  '/app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/app/settings/categories': typeof AppSettingsCategoriesRoute
  '/app/settings/rules': typeof AppSettingsRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/app/accounts'
    | '/app/budget'
    | '/app/cash-flow'
    | '/app/investments'
    | '/app/net-worth'
    | '/app/recurring'
    | '/app/transactions'
    | '/app/'
    | '/app/accounts/$accountId'
    | '/app/settings/categories'
    | '/app/settings/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/app/accounts'
    | '/app/budget'
    | '/app/cash-flow'
    | '/app/investments'
    | '/app/net-worth'
    | '/app/recurring'
    | '/app/transactions'
    | '/app'
    | '/app/accounts/$accountId'
    | '/app/settings/categories'
    | '/app/settings/rules'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/app/accounts'
    | '/app/budget'
    | '/app/cash-flow'
    | '/app/investments'
    | '/app/net-worth'
    | '/app/recurring'
    | '/app/transactions'
    | '/app/'
    | '/app/accounts/$accountId'
    | '/app/settings/categories'
    | '/app/settings/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/budget': {
      id: '/app/budget'
      path: '/budget'
      fullPath: '/app/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cash-flow': {
      id: '/app/cash-flow'
      path: '/cash-flow'
      fullPath: '/app/cash-flow'
      preLoaderRoute: typeof AppCashFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investments': {
      id: '/app/investments'
      path: '/investments'
      fullPath: '/app/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/net-worth': {
      id: '/app/net-worth'
      path: '/net-worth'
      fullPath: '/app/net-worth'
      preLoaderRoute: typeof AppNetWorthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recurring': {
      id: '/app/recurring'
      path: '/recurring'
      fullPath: '/app/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts/$accountId': {
      id: '/app/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/app/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/app/settings/categories': {
      id: '/app/settings/categories'
      path: '/settings/categories'
      fullPath: '/app/settings/categories'
      preLoaderRoute: typeof AppSettingsCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/rules': {
      id: '/app/settings/rules'
      path: '/settings/rules'
      fullPath: '/app/settings/rules'
      preLoaderRoute: typeof AppSettingsRulesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAccountsRouteChildren {
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppBudgetRoute: typeof AppBudgetRoute
  AppCashFlowRoute: typeof AppCashFlowRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppNetWorthRoute: typeof AppNetWorthRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsCategoriesRoute: typeof AppSettingsCategoriesRoute
  AppSettingsRulesRoute: typeof AppSettingsRulesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppBudgetRoute: AppBudgetRoute,
  AppCashFlowRoute: AppCashFlowRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppNetWorthRoute: AppNetWorthRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsCategoriesRoute: AppSettingsCategoriesRoute,
  AppSettingsRulesRoute: AppSettingsRulesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SsoCallbackRoute: SsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
