/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppBudgetRouteImport } from './routes/_app/budget'
import { Route as AppCashFlowRouteImport } from './routes/_app/cash-flow'
import { Route as AppInvestmentsRouteImport } from './routes/_app/investments'
import { Route as AppNetWorthRouteImport } from './routes/_app/net-worth'
import { Route as AppRecurringRouteImport } from './routes/_app/recurring'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts.$accountId'
import { Route as AppSettingsCategoriesRouteImport } from './routes/_app/settings.categories'
import { Route as AppSettingsRulesRouteImport } from './routes/_app/settings.rules'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppCashFlowRoute = AppCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppNetWorthRoute = AppNetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppSettingsCategoriesRoute = AppSettingsCategoriesRouteImport.update({
  id: '/settings/categories',
  path: '/settings/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRulesRoute = AppSettingsRulesRouteImport.update({
  id: '/settings/rules',
  path: '/settings/rules',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/accounts': typeof AppAccountsRouteWithChildren
  '/budget': typeof AppBudgetRoute
  '/cash-flow': typeof AppCashFlowRoute
  '/investments': typeof AppInvestmentsRoute
  '/net-worth': typeof AppNetWorthRoute
  '/recurring': typeof AppRecurringRoute
  '/transactions': typeof AppTransactionsRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/settings/categories': typeof AppSettingsCategoriesRoute
  '/settings/rules': typeof AppSettingsRulesRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/accounts': typeof AppAccountsRouteWithChildren
  '/budget': typeof AppBudgetRoute
  '/cash-flow': typeof AppCashFlowRoute
  '/investments': typeof AppInvestmentsRoute
  '/net-worth': typeof AppNetWorthRoute
  '/recurring': typeof AppRecurringRoute
  '/transactions': typeof AppTransactionsRoute
  '/': typeof AppIndexRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/settings/categories': typeof AppSettingsCategoriesRoute
  '/settings/rules': typeof AppSettingsRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/accounts': typeof AppAccountsRouteWithChildren
  '/_app/budget': typeof AppBudgetRoute
  '/_app/cash-flow': typeof AppCashFlowRoute
  '/_app/investments': typeof AppInvestmentsRoute
  '/_app/net-worth': typeof AppNetWorthRoute
  '/_app/recurring': typeof AppRecurringRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/_app/settings/categories': typeof AppSettingsCategoriesRoute
  '/_app/settings/rules': typeof AppSettingsRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/accounts'
    | '/budget'
    | '/cash-flow'
    | '/investments'
    | '/net-worth'
    | '/recurring'
    | '/transactions'
    | '/accounts/$accountId'
    | '/settings/categories'
    | '/settings/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/accounts'
    | '/budget'
    | '/cash-flow'
    | '/investments'
    | '/net-worth'
    | '/recurring'
    | '/transactions'
    | '/'
    | '/accounts/$accountId'
    | '/settings/categories'
    | '/settings/rules'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/sign-up'
    | '/_app/accounts'
    | '/_app/budget'
    | '/_app/cash-flow'
    | '/_app/investments'
    | '/_app/net-worth'
    | '/_app/recurring'
    | '/_app/transactions'
    | '/_app/'
    | '/_app/accounts/$accountId'
    | '/_app/settings/categories'
    | '/_app/settings/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-flow': {
      id: '/_app/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof AppCashFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investments': {
      id: '/_app/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/net-worth': {
      id: '/_app/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof AppNetWorthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring': {
      id: '/_app/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/settings/categories': {
      id: '/_app/settings/categories'
      path: '/settings/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AppSettingsCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/rules': {
      id: '/_app/settings/rules'
      path: '/settings/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof AppSettingsRulesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAccountsRouteChildren {
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppBudgetRoute: typeof AppBudgetRoute
  AppCashFlowRoute: typeof AppCashFlowRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppNetWorthRoute: typeof AppNetWorthRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsCategoriesRoute: typeof AppSettingsCategoriesRoute
  AppSettingsRulesRoute: typeof AppSettingsRulesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppBudgetRoute: AppBudgetRoute,
  AppCashFlowRoute: AppCashFlowRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppNetWorthRoute: AppNetWorthRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsCategoriesRoute: AppSettingsCategoriesRoute,
  AppSettingsRulesRoute: AppSettingsRulesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
